version: 2
updates:
- package-ecosystem: "docker"
  directory: ".devcontainer"
  schedule:
    interval: daily
    time: "05:30"
    timezone: Europe/London
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: daily
    time: "05:30"
    timezone: Europe/London
- package-ecosystem: nuget
  directory: "/"
  groups:
    Aspire:
      patterns:
        - Aspire.*
    OpenTelemetry:
      patterns:
        - OpenTelemetry*
    Polly:
      patterns:
        - Polly*
    xunit:
      patterns:
        - xunit*
  schedule:
    interval: daily
    time: "05:30"
    timezone: Europe/London
  open-pull-requests-limit: 99
- package-ecosystem: npm
  directory: "/src/DependabotHelper"
  groups:
    babel:
      patterns:
        - "@babel/*"
    jest:
      patterns:
        - "jest*"
    typescript-eslint:
      patterns:
        - "@typescript-eslint/*"
  schedule:
    interval: daily
    time: "05:30"
    timezone: Europe/London
  open-pull-requests-limit: 99
