name: build

on:
  push:
    branches: [ main ]
    paths-ignore:
    - '**/*.md'
    - '**/*.gitignore'
    - '**/*.gitattributes'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: dependabothelper
  AZURE_WEBAPP_PACKAGE_PATH: ./artifacts/publish
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_GENERATE_ASPNET_CERTIFICATE: false
  DOTNET_MULTILEVEL_LOOKUP: 0
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  NUGET_XMLDOC_MODE: skip
  WEBSITE_URL_PROD: https://dependabot.martincostello.com

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v2

    - name: Build, Test and Publish
      shell: pwsh
      run: ./build.ps1 -Runtime win10-x64

    - uses: codecov/codecov-action@v2.1.0
      name: Upload coverage to Codecov
      with:
        file: ./artifacts/coverage.cobertura.xml
        flags: ${{ matrix.codecov_os }}

    - name: Publish artifacts
      uses: actions/upload-artifact@v2
      if: ${{ runner.os == 'Windows' }}
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    - name: Publish screenshots
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: screenshots
        path: ./artifacts/screenshots/*
        if-no-files-found: ignore

    - name: Publish traces
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: traces
        path: ./artifacts/traces/*
        if-no-files-found: ignore

    - name: Publish videos
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: videos
        path: ./artifacts/videos/*
        if-no-files-found: ignore

  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: deploy-production
    needs: build
    runs-on: windows-latest
    concurrency: production_environment
    environment:
      name: production
      url: ${{ env.WEBSITE_URL_PROD }}

    steps:

    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: webapp

    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      id: deploy_production
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }}
