name: dependency-review

on:
  pull_request:
    branches:
      - main
      - dotnet-vnext
      - dotnet-nightly

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          filter: 'tree:0'
          show-progress: false

      - name: Review dependencies
        uses: actions/dependency-review-action@da24556b548a50705dd671f47852072ea4c105d9 # v4.7.1
        with:
          allow-licenses: '(MIT AND BSD-3-Clause),(MIT AND Zlib),(MIT OR Apache-2.0),(MIT OR CC0-1.0),0BSD,Apache-2.0,BlueOak-1.0.0,BSD-2-Clause,BSD-3-Clause,CC-BY-4.0,CC0-1.0,ISC,MIT,MIT-0,Python-2.0,LicenseRef-scancode-generic-cla AND MIT,LicenseRef-scancode-ms-typescript-msbuild-4.1.4,LicenseRef-scancode-ms-web-developer-tools-1.0 AND LicenseRef-scancode-ms-sql-server-compact-4.0 AND MIT
