name: lighthouse

on:
  pull_request:
    branches:
      - main
      - dotnet-vnext
      - dotnet-nightly
  workflow_dispatch:

permissions: {}

env:
  APPLICATION_URL: 'https://localhost:50001'
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true
  DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: 1
  NUGET_XMLDOC_MODE: skip
  TERM: xterm

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      contents: read

    steps:

    - name: Checkout code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        filter: 'tree:0'
        persist-credentials: false
        show-progress: false

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@d4c94342e560b34958eacfc5d055d21461ed1c5d # v5.0.0

    - name: Start website
      shell: pwsh
      env:
        APPLICATION_URL: ${{ env.APPLICATION_URL }}
        GitHub__ClientId: 'github-client-id'
        GitHub__ClientSecret: 'github-client-secret'
      run: |
        Start-Process nohup 'dotnet run --project ./src/DependabotHelper/DependabotHelper.csproj --configuration Release /p:EnableNETAnalyzers=false /p:EnforceCodeStyleInBuild=false'
        $StatusCode = 0
        $Attempts = 0
        While ($Attempts -lt 10) {
          $Response = Try {
            Invoke-WebRequest ${env:APPLICATION_URL} -SkipCertificateCheck
          } catch {
            $_.Exception.Response
          }
          $StatusCode = $Response.StatusCode
          If ($StatusCode -eq 200) {
            break
          }
          $Attempts++
          Start-Sleep -Seconds 10
        }
        If ($StatusCode -ne 200) {
          throw "Failed to successfully connect to website after $Attempts attempts."
        }
        New-Item -Path "${env:GITHUB_WORKSPACE}/artifacts/lighthouse" -ItemType Directory | Out-Null

    - name: Lighthouse
      uses: foo-software/lighthouse-check-action@a80267da2e0244b8a2e457a8575fc47590615852 # v12.0.1
      id: lighthouse
      with:
        device: 'all'
        gitHubAccessToken: ${{ secrets.LIGHTHOUSE_ACCESS_TOKEN }}
        outputDirectory: ${{ github.workspace }}/artifacts/lighthouse
        overridesJsonFile: ./.github/lighthouse.config.json
        prCommentEnabled: true
        urls: '${{ env.APPLICATION_URL }}/sign-in'
        wait: true

    - name: Check Lighthouse scores
      uses: foo-software/lighthouse-check-status-action@2b9d5101f7a0de86ddb153a0d77ad7046aac1052 # v3.0.1
      with:
        lighthouseCheckResults: ${{ steps.lighthouse.outputs.lighthouseCheckResults }}
        minAccessibilityScore: "100"
        minBestPracticesScore: "100"
        minPerformanceScore: "95"
        minProgressiveWebAppScore: "50"
        minSeoScore: "60"

    - name: Publish artifacts
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      if: ${{ !cancelled() }}
      with:
        name: lighthouse
        path: ${{ github.workspace }}/artifacts/lighthouse
        if-no-files-found: ignore
